### ISSUE TITLE
Enabling viewing of presentations on GitHub pages

### ISSUE THREAD

**Issue by bkmgit** [IETF-Hackathon/ietf110-project-presentations#3]
On needs to enable GitHub pages to be able to view the HTML template at:
http://ietf-hackathon.github.io/ietf110-project-presentations/hackathon-presentation-template.html

For example the file at:
https://github.com/bkmgit/tryremark
can be viewed at:
https://bkmgit.github.io/tryremark

Information on how to enable this feature is available at:
https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by eckelcu** [comment]
I configured GitHub Pages within the setting for the repo. The main page now renders as https://ietf-hackathon.github.io/ietf110-project-presentations/.

**Comment by eckelcu** [comment]
Does this resolve the issue @bkmgit ?

**Comment by eckelcu** [comment]
I set things up the same for IETF 111. The following pages appear to render correctly to me. @bkmgit, please have a look and let me know if this resolves the issue. If you know of a better solution, I'd be happy to give it a try.
https://ietf-hackathon.github.io/ietf111-project-presentations/
https://ietf-hackathon.github.io/ietf111-project-presentations/hackathon-presentation-template.html#7

**Comment by bkmgit** [comment]
@eckelcu  It is also possible to generate a pdf file from the slides. Videos will not embed, but some people prefer to have a pdf to download. An example is available at https://github.com/bkmgit/tryremark If this seems ok, would you want the pdfs in a separate folder in the same branch or in a different branch?

**Comment by bkmgit** [comment]
As it is working now, remaining issue is generating a pdf file #4
