### ISSUE TITLE
HTML template rendering to PDF

### ISSUE THREAD

**Issue by vlvassilev** [IETF-Hackathon/ietf110-project-presentations#4]
Looked into using the HTML presentation template but it was impossible to render it as a PDF. Printing from a Browser does not work well.

**Comment by eckelcu** [comment]
HI @vlvassilev, I am still learning how GitHub pages works. I enabled it for our repo (is was disabled by default). The repo now renders as https://ietf-hackathon.github.io/ietf110-project-presentations/.
What I did for the HTML template repo is open the file in my browser and then print from the browser, saving as a PDF. The result is what I have uploaded here. 
[IETF Hackathon - [Project Name].pdf](https://github.com/IETF-Hackathon/ietf110-project-presentations/files/6126349/IETF.Hackathon.-.Project.Name.pdf)

**Comment by eckelcu** [comment]
@vlvassilev,  let me know if this resolves the problem.

**Comment by vlvassilev** [comment]
The PDF is with dimensions that do not correspond to the actual presentation - vertical (portrait )instead of horizontal (landscape) orientation. It works but it would be nice if it resembled closer the actual presentation style.

Not a blocking issue for me.

**Comment by eckelcu** [comment]
Hi @vlvassilev  
The following render in landscape format now for me,
https://ietf-hackathon.github.io/ietf110-project-presentations/hackathon-presentation-template.html#1
https://ietf-hackathon.github.io/ietf111-project-presentations/hackathon-presentation-template.html#1

Let me know if this works for you.

**Comment by bkmgit** [comment]
Thanks for this. Demo for how to generate pdf at https://github.com/bkmgit/tryremark
A related question is where to put the resulting generated pdf files
https://github.com/IETF-Hackathon/ietf110-project-presentations/issues/3
Probably a separate folder or separate branch works with a description added to the README file with download links or instructions on where to download from.

**Comment by bkmgit** [comment]
One can also use [Rmd](https://rmarkdown.rstudio.com/) to generate [slides](https://bookdown.org/yihui/rmarkdown/ioslides-presentation.html), and then use [xaringanBuilder](https://github.com/jhelvy/xaringanBuilder) for conversion, but this is probably more complicated than needed for most presentations. [xaringan](https://github.com/yihui/xaringan) uses remark.js to generate slides, and has some nice [formatting examples](https://xaringan.gallery/examples).

**Comment by eckelcu** [comment]
@bkmgit, I do not have a strong preference, but I lean toward a separate folder. Would you want to give this a try for IETF 111?

**Comment by bkmgit** [comment]
Can be closed. Will be addressed in https://github.com/IETF-Hackathon/ietf111-project-presentations/issues/2

**Comment by bkmgit** [comment]
Addressed in https://github.com/IETF-Hackathon/ietf111-project-presentations/pull/3

**Comment by bkmgit** [comment]
@eckelcu Hopefully ok now.

**Comment by eckelcu** [comment]
Yes, I believe it is and will close this one.
